export const GET_SUPPLIERS_REQUEST = 'GET_SUPPLIERS_REQUEST';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAIL = 'GET_SUPPLIERS_FAIL';

export const CREATE_SUPPLIER_REQUEST = 'CREATE_SUPPLIER_REQUEST';
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
export const CREATE_SUPPLIER_FAIL = 'CREATE_SUPPLIER_FAIL';
export const CREATE_SUPPLIER_RESET = 'CREATE_SUPPLIER_RESET';

export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL';
export const DELETE_SUPPLIER_RESET = 'DELETE_SUPPLIER_RESET'; // Thêm hằng số này
export const DELETE_SUPPLIER_REQUEST = 'DELETE_SUPPLIER_REQUEST';

export const SUPPLIER_DETAILS_REQUEST = 'SUPPLIER_DETAILS_REQUEST';
export const SUPPLIER_DETAILS_SUCCESS = 'SUPPLIER_DETAILS_SUCCESS';
export const SUPPLIER_DETAILS_FAIL = 'SUPPLIER_DETAILS_FAIL';
export const SUPPLIER_DETAILS_RESET = 'SUPPLIER_DETAILS_RESET';

export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAIL = 'UPDATE_SUPPLIER_FAIL';
export const UPDATE_SUPPLIER_RESET = 'UPDATE_SUPPLIER_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';